# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Don't share the default synced folder
  config.vm.define "client1" do |ubuntu|
    ubuntu.vm.box = "robwc/minitrusty64"
    ubuntu.vm.hostname = "client1.example.com"
    ubuntu.vm.network "private_network",
      ip: "192.0.2.10",
      virtualbox__intnet: "neta"
    config.vm.synced_folder "", "/vagrant", disabled: true
  end

  config.vm.define "client2" do |ubuntu|
    ubuntu.vm.box = "robwc/minitrusty64"
    ubuntu.vm.hostname = "client2.example.com"
    ubuntu.vm.network "private_network",
      ip: "192.0.2.20",
      virtualbox__intnet: "neta"
    config.vm.synced_folder "", "/vagrant", disabled: true
  end


  config.vm.define "server1" do |ubuntu|
    ubuntu.vm.box = "robwc/minitrusty64"
    ubuntu.vm.hostname = "server.example.com"
    ubuntu.vm.network "private_network",
      ip: "198.51.100.10",
      virtualbox__intnet: "netb"
    config.vm.synced_folder "", "/vagrant", disabled: true
  end

  config.vm.define "JDDoS" do |dut|
    dut.vm.box = "JDDoS"
    dut.vm.network "private_network",
      ip: "192.0.2.1",
      virtualbox__intnet: "neta",
      nic_type: 'virtio'
    dut.vm.network "private_network",
      ip: "192.51.100.1",
      virtualbox__intnet: "netb",
      nic_type: 'virtio'
    dut.vm.synced_folder "", "/vagrant", disabled: true
  end

end
