# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Don't share the default synced folder
  config.vm.synced_folder "", "/vagrant", disabled: true

  config.vm.define "trusty1" do |ubuntu|
    ubuntu.vm.box = "robwc/minitrusty64"
    ubuntu.vm.hostname = "trusty.example.com"
    ubuntu.vm.network "private_network",
      ip: "192.0.2.10",
      virtualbox__intnet: "neta"
    config.vm.synced_folder "", "/vagrant", disabled: true
  end

  config.vm.define "trusty2" do |ubuntu|
    ubuntu.vm.box = "robwc/minitrusty64"
    ubuntu.vm.hostname = "trusty.example.com"
    ubuntu.vm.network "private_network",
      ip: "198.51.100.10",
      virtualbox__intnet: "netb"
    config.vm.synced_folder "", "/vagrant", disabled: true
  end

  config.vm.define "FFP" do |ubuntu|
    ubuntu.vm.box = "juniper/ffp-12.1X46-D20.5"
    ubuntu.vm.network "private_network",
      ip: "dhcp",
      virtualbox__intnet: "mgmt"
    ubuntu.vm.network "private_network",
      ip: "192.0.2.1",
      virtualbox__intnet: "neta"
    ubuntu.vm.network "private_network",
      ip: "192.51.100.1",
      virtualbox__intnet: "netb"
    config.vm.synced_folder "", "/vagrant", disabled: true
  end
end
